# Generated by Django 5.2.5 on 2025-08-22 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Tafera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('nomeSetor', models.CharField(max_length=90)),
                ('prioridade', models.CharField(choices=[('baixa', 'baixa'), ('media', 'media'), ('alta', 'alta')], max_length=5)),
                ('status', models.CharField(choices=[('a fazer', 'a fazer'), ('fazendo', 'fazendo'), ('pronto', 'pronto')], default='a fazer', max_length=10)),
                ('data_cadastro', models.DateField()),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toDo.usuario')),
            ],
        ),
    ]
