# Generated by Django 5.2.5 on 2025-08-22 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toDo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tafera',
            new_name='Tarefa',
        ),
    ]
