# Generated by Django 5.2.5 on 2025-09-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toDo', '0003_alter_usuario_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='data_cadastro',
            field=models.DateField(auto_now_add=True),
        ),
    ]
