# Generated by Django 5.2.5 on 2025-09-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toDo', '0005_alter_tarefa_descricao_alter_usuario_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('a fazer', 'a fazer'), ('fazendo', 'fazendo'), ('feito', 'feito')], default='a fazer', max_length=10),
        ),
    ]
