# Generated by Django 5.2.5 on 2025-09-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toDo', '0006_alter_tarefa_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
