# Generated by Django 5.2.5 on 2025-09-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toDo', '0007_alter_usuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
