# Generated by Django 5.2.5 on 2025-09-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toDo', '0008_alter_usuario_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.CharField(max_length=40),
        ),
    ]
