# Generated by Django 5.2.5 on 2025-09-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toDo', '0009_alter_usuario_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='descricao',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='nomeSetor',
            field=models.CharField(max_length=50),
        ),
    ]
