# Generated by Django 5.2.5 on 2025-09-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toDo', '0010_alter_tarefa_descricao_alter_tarefa_nomesetor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='nomeSetor',
            field=models.CharField(max_length=20),
        ),
    ]
