# Generated by Django 5.2.5 on 2025-09-29 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toDo', '0011_alter_tarefa_nomesetor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefa',
            old_name='idUsuario',
            new_name='usuario',
        ),
    ]
