# Generated by Django 5.2.5 on 2025-09-29 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toDo', '0012_rename_idusuario_tarefa_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefa',
            old_name='usuario',
            new_name='idUsuario',
        ),
    ]
